[versions]
agp = "8.3.0-alpha03"
kotlin = "1.9.0"
core-ktx = "1.12.0"
core-splashscreen = "1.0.1"
lifecycle = "2.6.2"
hilt = "2.48"
activity-compose = "1.7.2"
compose-bom = "2023.09.00"
androidx-tv = "1.0.0-alpha09"
navigation-compose = "2.7.2"
hilt-navigation-compose = "1.0.0"
leanback = "1.2.0-alpha03"
coil = "2.4.0"
coil-transformers = "1.0.6"
qrcode = "1.5.3"
timber = "5.0.1"
media3 = "1.1.1"
akdanmaku = "1.0.3"
datastore = "1.1.0-alpha03"
jsoup = "1.14.3"
rxjava3 = "3.1.7"
rxjava3-android = "3.0.2"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
runtime = { group = "androidx.compose.runtime", name = "runtime" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
runtime-rxjava3 = { group = "androidx.compose.runtime", name = "runtime-rxjava3" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "androidx-tv" }
tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "androidx-tv" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-transformers = { group = "jp.wasabeef.transformers", name = "coil", version.ref = "coil-transformers" }
coil-transformers-gpu = { group = "jp.wasabeef.transformers", name = "coil-gpu", version.ref = "coil-transformers" }
qrcode = { group = "com.github.alexzhirkevich", name = "custom-qr-generator", version.ref = "qrcode" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
media3 = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
akdanmaku = { group = "com.kuaishou", name = "akdanmaku", version.ref = "akdanmaku" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastore-preferences-rxjava3 = { group = "androidx.datastore", name = "datastore-preferences-rxjava3", version.ref = "datastore" }
rxjava3 = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava3"}
rxjava3-android = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxjava3-android"}
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }